/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.interfazfutbolistas;


import Liga.LigaController;
import Liga.Liga;
import Equipos.EquipoController;
import Equipos.Equipo;
import Futbolista.FutbolistaController;
import Futbolista.Futbolista;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author jaime
 */
public class interfazFutoblistas extends javax.swing.JFrame {
    //Variables Necesarias para Futbolista
    FutbolistaController controlador_fut = new FutbolistaController();
    boolean insertarFut = false;
    boolean modificarFut = false;
    boolean eliminarFut = false;
    File file_fut = new File ("Futbolistas.xml");
    int row;
    //Variables Necesarias para Equipo
    EquipoController controlador_equi = new EquipoController();
    boolean insertarEqui = false;
    boolean modificarEqui = false;
    boolean eliminarEqui = false;
    File file_equi = new File ("Equipos.xml");
    boolean EqeliminarConFk = false;
    //Variables Necesarias para Liga
    LigaController controlador_liga = new LigaController();
    boolean insertarLiga = false;
    boolean modificarLiga = false;
    boolean eliminarLiga = false;
    File file_liga = new File ("Ligas.xml");
    boolean eliminarLigaFk = false;
    int rowL ;
    /**
     * Creates new form interfazFutoblistas
     * @throws java.io.IOException
     */
    public interfazFutoblistas() throws IOException, ClassNotFoundException, FileNotFoundException, ParserConfigurationException, SAXException {
        initComponents();       
        if(file_fut.exists()){
            controlador_fut.LeerFichero();
            String matriz [][] = controlador_fut.datos_fut();
            mostrarTablaFut(matriz);
        }
        //Inicializacion de los botones/textBox Tabla futbolista
        BotonConfirmar.setVisible(false);
        BotonCancelar.setVisible(false);
        jLabel6.setVisible(false);
        DniFut.setVisible(false);
        DniFut.setEditable(false);
        NombreFut.setEditable(false);
        Apellido1Fut.setEditable(false);
        Apellido2Fut.setEditable(false);
        EdadFut.setEditable(false);
        
        if(file_equi.exists()){
            controlador_equi.LeerFichero();
            String matriz [][] = controlador_equi.datos_equi();
            mostrarTablaEqui(matriz);
        }
        ComboBoxEquipos.removeAllItems();
        for (int i = 0; i < controlador_fut.getFutbolistas().size(); i++){
            ComboBoxEquipos.addItem((controlador_fut.getFutbolistas(i).getDni()));
        }
        //Inicializacion de los botones/textBox Tabla Equipos
        ConfirmarEqui.setVisible(false);
        CancelarEqui.setVisible(false);
        jLabel1.setVisible(false);
        IdEqui.setVisible(false);
        IdEqui.setEditable(false);
        NombreEqui.setEditable(false);
        FundacionEqui.setEditable(false);
        EstadioEqui.setEditable(false);
        SociosEqui.setEditable(false);
        ComboBoxEquipos.setVisible(false);
        DniFutb.setVisible(true);
        DniFutb.setEditable(false);
        
        if(file_liga.exists()){
            controlador_liga.LeerFichero();
            String matriz [][] = controlador_liga.datos_liga();
            mostrarTablaLiga(matriz);
        }
        //Inicializacion de los botones/textBox Tabla Ligas
        jLabel14.setVisible(false);
        IdLiga.setVisible(false);
        ConfirmarLiga.setVisible(false);
        CancelarLiga.setVisible(false);
        IdLiga.setEditable(false);
        NombreLiga.setEditable(false);
        EquiposLiga.setEditable(false);
        InicioLiga.setEditable(false);
        FinLiga.setEditable(false);
        ComboBoxLigas.setVisible(false);
        IdEquiposLiga.setVisible(true);
        IdEquiposLiga.setEditable(false);
        
    }

    /**
     * This method is called fro8m within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        NombreFut = new javax.swing.JTextField();
        DniFut = new javax.swing.JTextField();
        Apellido1Fut = new javax.swing.JTextField();
        Apellido2Fut = new javax.swing.JTextField();
        BotonInsertar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonConfirmar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EdadFut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IdEqui = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEqui = new javax.swing.JTable();
        NombreEqui = new javax.swing.JTextField();
        SociosEqui = new javax.swing.JTextField();
        FundacionEqui = new javax.swing.JTextField();
        EstadioEqui = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BotonInsertarEqui = new javax.swing.JButton();
        BotonModificarEqui = new javax.swing.JButton();
        BotonEliminarEqui = new javax.swing.JButton();
        ConfirmarEqui = new javax.swing.JButton();
        CancelarEqui = new javax.swing.JButton();
        ComboBoxEquipos = new javax.swing.JComboBox<>();
        DniFutb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BotonInsertarLiga = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BotonEliminarLiga = new javax.swing.JButton();
        BotonModificarLiga = new javax.swing.JButton();
        ConfirmarLiga = new javax.swing.JButton();
        CancelarLiga = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLiga = new javax.swing.JTable();
        NombreLiga = new javax.swing.JTextField();
        IdLiga = new javax.swing.JTextField();
        EquiposLiga = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        InicioLiga = new javax.swing.JTextField();
        FinLiga = new javax.swing.JTextField();
        ComboBoxLigas = new javax.swing.JComboBox<>();
        IdEquiposLiga = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        NombreFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFutActionPerformed(evt);
            }
        });

        DniFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniFutActionPerformed(evt);
            }
        });

        Apellido1Fut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1FutActionPerformed(evt);
            }
        });

        Apellido2Fut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido2FutActionPerformed(evt);
            }
        });

        BotonInsertar.setText("Insertar");
        BotonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarActionPerformed(evt);
            }
        });

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Dni");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido1");

        jLabel9.setText("Apellido2");

        jLabel10.setText("FUTBOLISTAS");

        EdadFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadFutActionPerformed(evt);
            }
        });

        jLabel11.setText("Edad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonConfirmar)
                .addGap(18, 18, 18)
                .addComponent(BotonCancelar)
                .addGap(9, 9, 9))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreFut)
                    .addComponent(Apellido1Fut)
                    .addComponent(Apellido2Fut)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DniFut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EdadFut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DniFut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreFut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(Apellido1Fut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido2Fut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(EdadFut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConfirmar)
                    .addComponent(BotonCancelar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Futbolistas", jPanel2);

        IdEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdEquiActionPerformed(evt);
            }
        });

        jTableEqui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEquiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableEqui);

        SociosEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SociosEquiActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Fecha de Fundación");

        jLabel4.setText("Estadio");

        jLabel5.setText("Número de Socios");

        jLabel12.setText("EQUIPOS");

        BotonInsertarEqui.setText("Insertar");
        BotonInsertarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarEquiActionPerformed(evt);
            }
        });

        BotonModificarEqui.setText("Modificar");
        BotonModificarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEquiActionPerformed(evt);
            }
        });

        BotonEliminarEqui.setText("Eliminar");
        BotonEliminarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarEquiActionPerformed(evt);
            }
        });

        ConfirmarEqui.setText("Confirmar");
        ConfirmarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEquiActionPerformed(evt);
            }
        });

        CancelarEqui.setText("Cancelar");
        CancelarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEquiActionPerformed(evt);
            }
        });

        ComboBoxEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEquiposActionPerformed(evt);
            }
        });

        DniFutb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniFutbActionPerformed(evt);
            }
        });

        jLabel19.setText("DniFutbolistas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BotonInsertarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonModificarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(477, 477, 477)
                        .addComponent(ConfirmarEqui)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarEqui))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SociosEqui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(ComboBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DniFutb))
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EstadioEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FundacionEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(IdEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FundacionEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstadioEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(SociosEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DniFutb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarEqui)
                    .addComponent(CancelarEqui))
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonInsertarEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        jTabbedPane2.addTab("Equipos", jPanel3);

        BotonInsertarLiga.setText("Insertar");
        BotonInsertarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarLigaActionPerformed(evt);
            }
        });

        jLabel13.setText("Fecha Fin");

        BotonEliminarLiga.setText("Eliminar");
        BotonEliminarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarLigaActionPerformed(evt);
            }
        });

        BotonModificarLiga.setText("Modificar");
        BotonModificarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarLigaActionPerformed(evt);
            }
        });

        ConfirmarLiga.setText("Confirmar");
        ConfirmarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarLigaActionPerformed(evt);
            }
        });

        CancelarLiga.setText("Cancelar");
        CancelarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarLigaActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        jLabel15.setText("Nombre");

        jLabel16.setText("Nº Equipos");

        jLabel17.setText("Fecha Inicio");

        jTableLiga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLigaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLiga);

        NombreLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreLigaActionPerformed(evt);
            }
        });

        IdLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdLigaActionPerformed(evt);
            }
        });

        EquiposLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquiposLigaActionPerformed(evt);
            }
        });

        jLabel18.setText("LIGAS");

        InicioLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioLigaActionPerformed(evt);
            }
        });

        FinLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinLigaActionPerformed(evt);
            }
        });

        ComboBoxLigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLigasActionPerformed(evt);
            }
        });

        IdEquiposLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdEquiposLigaActionPerformed(evt);
            }
        });

        jLabel20.setText("Id_Equipos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ConfirmarLiga)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarLiga)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ComboBoxLigas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdEquiposLiga, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreLiga)
                            .addComponent(EquiposLiga)
                            .addComponent(InicioLiga)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdLiga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FinLiga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BotonInsertarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonModificarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(EquiposLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InicioLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(2, 2, 2)
                        .addComponent(FinLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdEquiposLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxLigas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonInsertarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEliminarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarLiga)
                    .addComponent(CancelarLiga))
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("Ligas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void MostrarAtributosFutbolistas(int row){
        DniFut.setText(String.valueOf(controlador_fut.getFutbolistas(row).getDni()));
        NombreFut.setText(String.valueOf(controlador_fut.getFutbolistas(row).getNombre()));
        Apellido1Fut.setText(String.valueOf(controlador_fut.getFutbolistas(row).getApellido1()));
        Apellido2Fut.setText(String.valueOf(controlador_fut.getFutbolistas(row).getApellido2()));
        EdadFut.setText(String.valueOf(controlador_fut.getFutbolistas(row).getEdad()));
    }
    public void MostrarAtributosEquipos(int row){
        IdEqui.setText(String.valueOf(controlador_equi.getEquipos(row).getEquipo_ID()));
        NombreEqui.setText(String.valueOf(controlador_equi.getEquipos(row).getNombre_equipo()));
        FundacionEqui.setText(String.valueOf(controlador_equi.getEquipos(row).getFecha_fundacion()));
        EstadioEqui.setText(String.valueOf(controlador_equi.getEquipos(row).getNombre_campo()));
        SociosEqui.setText(String.valueOf(controlador_equi.getEquipos(row).getNumero_socios()));
        DniFutb.setText(String.valueOf(controlador_equi.getEquipos(row).getDniFut()));
    }
    public void MostrarAtributosLiga(int row){
        IdLiga.setText(String.valueOf(controlador_liga.getLigas(row).getLiga_ID()));
        NombreLiga.setText(String.valueOf(controlador_liga.getLigas(row).getNombre_liga()));
        EquiposLiga.setText(String.valueOf(controlador_liga.getLigas(row).getNumero_equipos()));
        InicioLiga.setText(String.valueOf(controlador_liga.getLigas(row).getFecha_inicio()));
        FinLiga.setText(String.valueOf(controlador_liga.getLigas(row).getFecha_fin()));
        IdEquiposLiga.setText(String.valueOf(controlador_liga.getLigas(row).getId_equipos()));
    }
    
    public void mostrarTablaFut(String mat [][]){
        jTable2.setModel(new javax.swing.table.DefaultTableModel(mat, 
                new String []{"Nombre", "Apellidos1",}));
    }
    public void mostrarTablaEqui(String mat [][]){
        jTableEqui.setModel(new javax.swing.table.DefaultTableModel(mat, 
                new String []{"Nombre", "NombreCampo"}));
    }
    public void mostrarTablaLiga(String mat [][]){
        jTableLiga.setModel(new javax.swing.table.DefaultTableModel(mat, 
                new String []{"Nombre", "NumeroEquipos"}));
    }
  
    private void Apellido2FutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido2FutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2FutActionPerformed

    private void Apellido1FutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1FutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1FutActionPerformed

    private void EdadFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadFutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadFutActionPerformed
    //Boton Insertar Futbolista
    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarActionPerformed
        // TODO add your handling code here:
        
        jLabel6.setVisible(true);
        DniFut.setVisible(true);
        insertarFut = true;
        BotonConfirmar.setVisible(true);
        BotonCancelar.setVisible(true);
        BotonInsertar.setEnabled(false);
        BotonModificar.setEnabled(false);
        BotonEliminar.setEnabled(false);
        DniFut.setEditable(true);
        NombreFut.setEditable(true);
        Apellido1Fut.setEditable(true);
        Apellido2Fut.setEditable(true);
        EdadFut.setEditable(true);
        DniFut.setText(null);
        NombreFut.setText(null);
        Apellido1Fut.setText(null);
        Apellido2Fut.setText(null);
        EdadFut.setText(null);
        
    }//GEN-LAST:event_BotonInsertarActionPerformed
    //Boton modificar Futbolista
    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        DniFut.setVisible(false);
        modificarFut = true;
        BotonConfirmar.setVisible(true);
        BotonCancelar.setVisible(true);
        BotonInsertar.setEnabled(false);
        BotonModificar.setEnabled(false);
        BotonEliminar.setEnabled(false);
        DniFut.setEditable(true);
        NombreFut.setEditable(true);
        Apellido1Fut.setEditable(true);
        Apellido2Fut.setEditable(true);
        EdadFut.setEditable(true);
        
    }//GEN-LAST:event_BotonModificarActionPerformed
    //Boton Eliminar Futbolista
    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        DniFut.setVisible(false);
        eliminarFut = true;
        BotonConfirmar.setVisible(true);
        BotonCancelar.setVisible(true);
        BotonInsertar.setEnabled(false);
        BotonModificar.setEnabled(false);
        BotonEliminar.setEnabled(false);
        DniFut.setEditable(false);
        NombreFut.setEditable(false);
        Apellido1Fut.setEditable(false);
        Apellido2Fut.setEditable(false);
        EdadFut.setEditable(false);
        DniFut.setEditable(false);
        NombreFut.setEditable(false);
        Apellido1Fut.setEditable(false);
        Apellido2Fut.setEditable(false);
        EdadFut.setEditable(false);
    }//GEN-LAST:event_BotonEliminarActionPerformed
    //Boton Confirmar Futbolista
    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
        // TODO add your handling code here:
        if(insertarFut == true){
            Futbolista fut = new Futbolista(DniFut.getText(),NombreFut.getText(),
                    Apellido1Fut.getText(),Apellido2Fut.getText(),Integer.valueOf(EdadFut.getText()));
            controlador_fut.guardarFutbolistas(fut);
            String matriz [][] = controlador_fut.datos_fut();
            mostrarTablaFut(matriz);
            try {
                controlador_fut.guardarFutbolistasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            DniFut.setText(null);
            NombreFut.setText(null);
            Apellido1Fut.setText(null);
            Apellido2Fut.setText(null);
            EdadFut.setText(null);
            BotonConfirmar.setVisible(false);
            BotonCancelar.setVisible(false);
            BotonInsertar.setEnabled(true);
            BotonModificar.setEnabled(true);
            BotonEliminar.setEnabled(true);
            insertarFut = false;
            DniFut.setEditable(false);
            NombreFut.setEditable(false);
            Apellido1Fut.setEditable(false);
            Apellido2Fut.setEditable(false);
            EdadFut.setEditable(false);
        }
        else if (modificarFut == true){
            
            controlador_fut.getFutbolistas(row).setDni(DniFut.getText());
            controlador_fut.getFutbolistas(row).setNombre(NombreFut.getText());
            controlador_fut.getFutbolistas(row).setApellido1(Apellido1Fut.getText());
            controlador_fut.getFutbolistas(row).setApellido2(Apellido2Fut.getText());
            controlador_fut.getFutbolistas(row).setEdad(Integer.valueOf(EdadFut.getText()));
            
            String matriz [][] = controlador_fut.datos_fut();
            mostrarTablaFut(matriz);
            try {
                controlador_fut.guardarFutbolistasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel6.setVisible(false);
            DniFut.setVisible(false);
            DniFut.setText(null);
            NombreFut.setText(null);
            Apellido1Fut.setText(null);
            Apellido2Fut.setText(null);
            EdadFut.setText(null);
            BotonConfirmar.setVisible(false);
            BotonCancelar.setVisible(false);
            BotonInsertar.setEnabled(true);
            BotonModificar.setEnabled(true);
            BotonEliminar.setEnabled(true);
            modificarFut = false;
            DniFut.setEditable(false);
            NombreFut.setEditable(false);
            Apellido1Fut.setEditable(false);
            Apellido2Fut.setEditable(false);
            EdadFut.setEditable(false);
        }
        else if(eliminarFut == true){
            int rowE = jTable2.getSelectedRow();
            for(int i = 0; i < controlador_equi.getEquipos().size(); i++){
                if(controlador_equi.getEquipos(i).getDniFut() == controlador_fut.getFutbolistas(rowE).getDni()){
                    EqeliminarConFk = true;
                }
            }
            if(EqeliminarConFk == false){
                controlador_fut.getFutbolistas().remove(rowE);
            try {
                controlador_fut.guardarFutbolistasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se puede Eliminar el Futbolista, tiene clave foránea");
            }
            String matriz [][] = controlador_fut.datos_fut();
            mostrarTablaFut(matriz);
            jLabel6.setVisible(false);
            DniFut.setVisible(false);
            DniFut.setText(null);
            NombreFut.setText(null);
            Apellido1Fut.setText(null);
            Apellido2Fut.setText(null);
            EdadFut.setText(null);
            BotonConfirmar.setVisible(false);
            BotonCancelar.setVisible(false);
            BotonInsertar.setEnabled(true);
            BotonModificar.setEnabled(true);
            BotonEliminar.setEnabled(true);
            eliminarFut = false;
            EqeliminarConFk = false;
            DniFut.setEditable(false);
            NombreFut.setEditable(false);
            Apellido1Fut.setEditable(false);
            Apellido2Fut.setEditable(false);
            EdadFut.setEditable(false);
        }             
        
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    private void DniFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniFutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniFutActionPerformed

    private void NombreFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFutActionPerformed
    //Boton Cancelar Futoblista
    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
            jLabel6.setVisible(false);
            DniFut.setVisible(false);
            DniFut.setText(null);
            NombreFut.setText(null);
            Apellido1Fut.setText(null);
            Apellido2Fut.setText(null);
            EdadFut.setText(null);
            BotonConfirmar.setVisible(false);
            BotonCancelar.setVisible(false);
            BotonInsertar.setEnabled(true);
            BotonModificar.setEnabled(true);
            BotonEliminar.setEnabled(true);
            IdEqui.setEditable(false);
            NombreEqui.setEditable(false);
            FundacionEqui.setEditable(false);
            EstadioEqui.setEditable(false);
            SociosEqui.setEditable(false);
            DniFutb.setEditable(false);
            
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void IdEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdEquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdEquiActionPerformed

    private void SociosEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SociosEquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SociosEquiActionPerformed
    //Boton Insertar Equipo
    private void BotonInsertarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarEquiActionPerformed
        ComboBoxEquipos.removeAllItems();
        for (int i = 0; i < controlador_fut.getFutbolistas().size(); i++){
            ComboBoxEquipos.addItem((controlador_fut.getFutbolistas(i).getDni()));
        }
        jLabel1.setVisible(true);
        IdEqui.setVisible(true);
        insertarEqui = true;
        ConfirmarEqui.setVisible(true);
        CancelarEqui.setVisible(true);
        BotonInsertarEqui.setEnabled(false);
        BotonModificarEqui.setEnabled(false);
        BotonEliminarEqui.setEnabled(false);
        IdEqui.setEditable(true);
        NombreEqui.setEditable(true);
        FundacionEqui.setEditable(true);
        EstadioEqui.setEditable(true);
        SociosEqui.setEditable(true);
        ComboBoxEquipos.setVisible(true);
        DniFutb.setVisible(false);
        IdEqui.setText(null);
        NombreEqui.setText(null);
        FundacionEqui.setText(null);
        EstadioEqui.setText(null);
        SociosEqui.setText(null);
        DniFutb.setText(null);
        
    }//GEN-LAST:event_BotonInsertarEquiActionPerformed
    //Boton Insertar Liga
    private void BotonInsertarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarLigaActionPerformed
        ComboBoxLigas.removeAllItems();
        for (int i = 0; i < controlador_equi.getEquipos().size(); i++){
            ComboBoxLigas.addItem((controlador_equi.getEquipos(i).getEquipo_ID()));
        }
        jLabel14.setVisible(true);
        IdLiga.setVisible(true);
        insertarLiga = true;
        ConfirmarLiga.setVisible(true);
        CancelarLiga.setVisible(true);
        BotonInsertarLiga.setEnabled(false);
        BotonModificarLiga.setEnabled(false);
        BotonEliminarLiga.setEnabled(false);
        IdLiga.setEditable(true);
        NombreLiga.setEditable(true);
        EquiposLiga.setEditable(true);
        InicioLiga.setEditable(true);
        FinLiga.setEditable(true);
        ComboBoxLigas.setVisible(true);
        IdEquiposLiga.setVisible(false);
        IdLiga.setText(null);
        NombreLiga.setText(null);
        EquiposLiga.setText(null);
        InicioLiga.setText(null);
        FinLiga.setText(null);
        
    }//GEN-LAST:event_BotonInsertarLigaActionPerformed
    //Boton Eliminar Liga
    private void BotonEliminarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarLigaActionPerformed
        jLabel14.setVisible(false);
        IdLiga.setVisible(false);
        eliminarLiga = true;
        ConfirmarLiga.setVisible(true);
        CancelarLiga.setVisible(true);
        BotonInsertarLiga.setEnabled(false);
        BotonModificarLiga.setEnabled(false);
        BotonEliminarLiga.setEnabled(false);
        ComboBoxLigas.setVisible(false);
        IdEquiposLiga.setVisible(true);
        IdLiga.setEditable(false);
        NombreLiga.setEditable(false);
        EquiposLiga.setEditable(false);
        InicioLiga.setEditable(false);
        FinLiga.setEditable(false);
        IdEquiposLiga.setEditable(false);
        
    }//GEN-LAST:event_BotonEliminarLigaActionPerformed
    //Boton Modificar Liga
    private void BotonModificarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarLigaActionPerformed
        ComboBoxLigas.removeAllItems();
        for (int i = 0; i < controlador_equi.getEquipos().size(); i++){
            ComboBoxLigas.addItem((controlador_equi.getEquipos(i).getEquipo_ID()));
        }
        jLabel14.setVisible(false);
        IdLiga.setVisible(false);
        modificarLiga = true;
        ConfirmarLiga.setVisible(true);
        CancelarLiga.setVisible(true);
        BotonInsertarLiga.setEnabled(false);
        BotonModificarLiga.setEnabled(false);
        BotonEliminarLiga.setEnabled(false);
        IdLiga.setEditable(true);
        NombreLiga.setEditable(true);
        EquiposLiga.setEditable(true);
        InicioLiga.setEditable(true);
        FinLiga.setEditable(true);
        ComboBoxLigas.setVisible(true);
        IdEquiposLiga.setVisible(false);
        
    }//GEN-LAST:event_BotonModificarLigaActionPerformed
    //Boton Confirmar Liga
    private void ConfirmarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarLigaActionPerformed
        if(insertarLiga == true){
            Liga lig = new Liga(IdLiga.getText(),NombreLiga.getText(),
                    Integer.valueOf(EquiposLiga.getText()),InicioLiga.getText(),FinLiga.getText(),
                    (String) ComboBoxLigas.getSelectedItem());
            controlador_liga.guardarLigas(lig);
            String matriz [][] = controlador_liga.datos_liga();
            mostrarTablaLiga(matriz);
            try {
                controlador_liga.guardarLigasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            IdLiga.setText(null);
            NombreLiga.setText(null);
            EquiposLiga.setText(null);
            InicioLiga.setText(null);
            FinLiga.setText(null);
            ConfirmarLiga.setVisible(false);
            CancelarLiga.setVisible(false);
            BotonInsertarLiga.setEnabled(true);
            BotonModificarLiga.setEnabled(true);
            BotonEliminarLiga.setEnabled(true);
            insertarLiga = false;
            ComboBoxLigas.setVisible(false);
            IdEquiposLiga.setVisible(true);
            IdLiga.setEditable(false);
            NombreLiga.setEditable(false);
            EquiposLiga.setEditable(false);
            InicioLiga.setEditable(false);
            FinLiga.setEditable(false);
            IdEquiposLiga.setEditable(false);
        }
        else if (modificarLiga == true){
            
            controlador_liga.getLigas(rowL).setLiga_ID(IdLiga.getText());
            controlador_liga.getLigas(rowL).setNombre_liga(NombreLiga.getText());
            controlador_liga.getLigas(rowL).setNumero_equipos(Integer.valueOf(EquiposLiga.getText()));
            controlador_liga.getLigas(rowL).setFecha_inicio(InicioLiga.getText());
            controlador_liga.getLigas(rowL).setFecha_fin(FinLiga.getText());
            controlador_liga.getLigas(rowL).setId_equipos((String) ComboBoxLigas.getSelectedItem());
            
            String matriz [][] = controlador_liga.datos_liga();
            mostrarTablaLiga(matriz);
            try {
                controlador_liga.guardarLigasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel14.setVisible(false);
            IdLiga.setVisible(false);
            IdLiga.setText(null);
            NombreLiga.setText(null);
            EquiposLiga.setText(null);
            InicioLiga.setText(null);
            FinLiga.setText(null);
            IdEquiposLiga.setText(null);
            ConfirmarLiga.setVisible(false);
            CancelarLiga.setVisible(false);
            BotonInsertarLiga.setEnabled(true);
            BotonModificarLiga.setEnabled(true);
            BotonEliminarLiga.setEnabled(true);
            modificarLiga = false;
            ComboBoxLigas.setVisible(false);
            IdEquiposLiga.setVisible(true);
            IdLiga.setEditable(false);
            NombreLiga.setEditable(false);
            EquiposLiga.setEditable(false);
            InicioLiga.setEditable(false);
            FinLiga.setEditable(false);
            IdEquiposLiga.setEditable(false);
        }
        else if(eliminarLiga == true){
            controlador_liga.getLigas().remove(rowL);
            String matriz [][] = controlador_liga.datos_liga();
            mostrarTablaLiga(matriz);
            try {
                controlador_liga.guardarLigasFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel14.setVisible(false);
            IdLiga.setVisible(false);
            IdLiga.setText(null);
            NombreLiga.setText(null);
            EquiposLiga.setText(null);
            InicioLiga.setText(null);
            FinLiga.setText(null);
            IdEquiposLiga.setText(null);
            ConfirmarLiga.setVisible(false);
            CancelarLiga.setVisible(false);
            BotonInsertarLiga.setEnabled(true);
            BotonModificarLiga.setEnabled(true);
            BotonEliminarLiga.setEnabled(true);
            eliminarLiga = false;
            ComboBoxLigas.setVisible(false);
            IdEquiposLiga.setVisible(true);
            IdLiga.setEditable(false);
            NombreLiga.setEditable(false);
            EquiposLiga.setEditable(false);
            InicioLiga.setEditable(false);
            FinLiga.setEditable(false);
            IdEquiposLiga.setEditable(false);
            
        }            
    }//GEN-LAST:event_ConfirmarLigaActionPerformed
    //Boton Cancelar Liga
    private void CancelarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarLigaActionPerformed
            jLabel14.setVisible(false);
            IdLiga.setVisible(false);
            IdLiga.setText(null);
            NombreLiga.setText(null);
            EquiposLiga.setText(null);
            InicioLiga.setText(null);
            FinLiga.setText(null);
            IdEquiposLiga.setText(null);
            ConfirmarLiga.setVisible(false);
            CancelarLiga.setVisible(false);
            BotonInsertarLiga.setEnabled(true);
            BotonModificarLiga.setEnabled(true);
            BotonEliminarLiga.setEnabled(true);
            ComboBoxLigas.setVisible(false);
            IdEquiposLiga.setVisible(true);
            IdLiga.setEditable(false);
            NombreLiga.setEditable(false);
            EquiposLiga.setEditable(false);
            InicioLiga.setEditable(false);
            FinLiga.setEditable(false);
            IdEquiposLiga.setEditable(false);
    }//GEN-LAST:event_CancelarLigaActionPerformed

    private void NombreLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreLigaActionPerformed

    private void IdLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdLigaActionPerformed

    private void EquiposLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquiposLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquiposLigaActionPerformed

    private void InicioLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioLigaActionPerformed

    private void FinLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinLigaActionPerformed
    //Boton Confirmar Equipo
    private void ConfirmarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEquiActionPerformed
                   
        if(insertarEqui == true){
            Equipo equip = new Equipo (IdEqui.getText(),NombreEqui.getText(),
                    FundacionEqui.getText(),EstadioEqui.getText(),Integer.valueOf(SociosEqui.getText()), 
                    (String) ComboBoxEquipos.getSelectedItem());
            controlador_equi.guardarEquipos(equip);
            String matriz [][] = controlador_equi.datos_equi();
            mostrarTablaEqui(matriz);
            try {
                controlador_equi.guardarEquiposFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            IdEqui.setText(null);
            NombreEqui.setText(null);
            FundacionEqui.setText(null);
            EstadioEqui.setText(null);
            SociosEqui.setText(null);
            DniFutb.setText(null);
            ConfirmarEqui.setVisible(false);
            CancelarEqui.setVisible(false);
            BotonInsertarEqui.setEnabled(true);
            BotonModificarEqui.setEnabled(true);
            BotonEliminarEqui.setEnabled(true);
            insertarEqui = false;
            ComboBoxEquipos.setVisible(false);
            DniFutb.setVisible(true);
            
        }
        else if (modificarEqui == true){
            int rowE = jTableEqui.getSelectedRow();
            controlador_equi.getEquipos(rowE).setEquipo_ID(IdEqui.getText());
            controlador_equi.getEquipos(rowE).setNombre_equipo(NombreEqui.getText());
            controlador_equi.getEquipos(rowE).setFecha_fundacion(FundacionEqui.getText());
            controlador_equi.getEquipos(rowE).setNombre_campo(EstadioEqui.getText());
            controlador_equi.getEquipos(rowE).setNumero_socios(Integer.valueOf(SociosEqui.getText()));
            controlador_equi.getEquipos(rowE).setDniFut((String) ComboBoxEquipos.getSelectedItem());
            
            String matriz [][] = controlador_equi.datos_equi();
            mostrarTablaEqui(matriz);
            try {
                controlador_equi.guardarEquiposFichero();
            } catch (IOException ex) {
                Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel1.setVisible(false);
            IdEqui.setVisible(false);
            IdEqui.setText(null);
            NombreEqui.setText(null);
            FundacionEqui.setText(null);
            EstadioEqui.setText(null);
            SociosEqui.setText(null);
            DniFutb.setText(null);
            ConfirmarEqui.setVisible(false);
            CancelarEqui.setVisible(false);
            BotonInsertarEqui.setEnabled(true);
            BotonModificarEqui.setEnabled(true);
            BotonEliminarEqui.setEnabled(true);
            insertarEqui = false;
            ComboBoxEquipos.setVisible(false);
            DniFutb.setVisible(true);
        }
        else if(eliminarEqui == true){
            int rowE = jTableEqui.getSelectedRow();
            for(int i = 0; i < controlador_liga.getLigas().size(); i++){
                if(controlador_liga.getLigas(i).getId_equipos() == controlador_equi.getEquipos(rowE).getEquipo_ID()){
                    eliminarLigaFk = true;
                }
            }
            if(eliminarLigaFk == false){
                controlador_equi.getEquipos().remove(rowE);
                try {
                    controlador_equi.guardarEquiposFichero();
                } catch (IOException ex) {
                    Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se puede Eliminar el Equipo, tiene clave foránea");
            }
            String matriz [][] = controlador_equi.datos_equi();
            mostrarTablaEqui(matriz);
            jLabel1.setVisible(false);
            IdEqui.setVisible(false);
            IdEqui.setText(null);
            NombreEqui.setText(null);
            FundacionEqui.setText(null);
            EstadioEqui.setText(null);
            SociosEqui.setText(null);
            DniFutb.setText(null);
            ConfirmarEqui.setVisible(false);
            CancelarEqui.setVisible(false);
            BotonInsertarEqui.setEnabled(true);
            BotonModificarEqui.setEnabled(true);
            BotonEliminarEqui.setEnabled(true);
            insertarEqui = false;
            ComboBoxEquipos.setVisible(false);
            DniFutb.setVisible(true);
            eliminarLigaFk = false;
        }
    }//GEN-LAST:event_ConfirmarEquiActionPerformed
    //Boton Cancelar Equipo
    private void CancelarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEquiActionPerformed
        jLabel1.setVisible(false);
        IdEqui.setVisible(false);
        IdEqui.setText(null);
        NombreEqui.setText(null);
        FundacionEqui.setText(null);
        EstadioEqui.setText(null);
        SociosEqui.setText(null);
        DniFutb.setText(null);
        ConfirmarEqui.setVisible(false);
        CancelarEqui.setVisible(false);
        BotonInsertarEqui.setEnabled(true);
        BotonModificarEqui.setEnabled(true);
        BotonEliminarEqui.setEnabled(true);
        ComboBoxEquipos.setVisible(false);
        DniFutb.setVisible(true);
        IdEqui.setText(null);
        NombreEqui.setText(null);
        FundacionEqui.setText(null);
        EstadioEqui.setText(null);
        SociosEqui.setText(null);
        DniFutb.setText(null);
        IdEqui.setEditable(false);
        NombreEqui.setEditable(false);
        FundacionEqui.setEditable(false);
        EstadioEqui.setEditable(false);
        SociosEqui.setEditable(false);
        DniFutb.setEditable(false);
    }//GEN-LAST:event_CancelarEquiActionPerformed
    //Boton Eliminar Equi
    private void BotonEliminarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarEquiActionPerformed
        jLabel1.setVisible(false);
        IdEqui.setVisible(false);
        eliminarEqui = true;
        ConfirmarEqui.setVisible(true);
        CancelarEqui.setVisible(true);
        BotonInsertarEqui.setEnabled(false);
        BotonModificarEqui.setEnabled(false);
        BotonEliminarEqui.setEnabled(false);
        ComboBoxEquipos.setVisible(false);
        DniFutb.setVisible(true);
        IdEqui.setEditable(false);
        NombreEqui.setEditable(false);
        FundacionEqui.setEditable(false);
        EstadioEqui.setEditable(false);
        SociosEqui.setEditable(false);
        DniFutb.setEditable(false);
        IdEqui.setText(null);
        NombreEqui.setText(null);
        FundacionEqui.setText(null);
        EstadioEqui.setText(null);
        SociosEqui.setText(null);
        DniFutb.setText(null);
    }//GEN-LAST:event_BotonEliminarEquiActionPerformed
    //Boton Modificar Equipo
    private void BotonModificarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEquiActionPerformed
        ComboBoxEquipos.removeAllItems();
        for (int i = 0; i < controlador_fut.getFutbolistas().size(); i++){
            ComboBoxEquipos.addItem((controlador_fut.getFutbolistas(i).getDni()));
        }
        jLabel1.setVisible(false);
        IdEqui.setVisible(false);
        modificarEqui = true;
        ConfirmarEqui.setVisible(true);
        CancelarEqui.setVisible(true);
        BotonInsertarEqui.setEnabled(false);
        BotonModificarEqui.setEnabled(false);
        BotonEliminarEqui.setEnabled(false);
        IdEqui.setEditable(true);
        NombreEqui.setEditable(true);
        FundacionEqui.setEditable(true);
        EstadioEqui.setEditable(true);
        SociosEqui.setEditable(true);
        ComboBoxEquipos.setVisible(true);
        DniFutb.setVisible(false);
    }//GEN-LAST:event_BotonModificarEquiActionPerformed

    private void DniFutbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniFutbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniFutbActionPerformed

    private void jTableEquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEquiMouseClicked
        // TODO add your handling code here:
        int rowE = jTableEqui.getSelectedRow();
        MostrarAtributosEquipos(rowE);
    }//GEN-LAST:event_jTableEquiMouseClicked

    private void jTableLigaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLigaMouseClicked
        int rowL = jTableLiga.getSelectedRow();
        MostrarAtributosLiga(rowL);
    }//GEN-LAST:event_jTableLigaMouseClicked

    private void IdEquiposLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdEquiposLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdEquiposLigaActionPerformed

    private void ComboBoxLigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLigasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLigasActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int rowF = jTable2.getSelectedRow();
        MostrarAtributosFutbolistas(rowF);
    }//GEN-LAST:event_jTable2MouseClicked

    private void ComboBoxEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new interfazFutoblistas().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParserConfigurationException ex) {
                    Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    Logger.getLogger(interfazFutoblistas.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1Fut;
    private javax.swing.JTextField Apellido2Fut;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonEliminarEqui;
    private javax.swing.JButton BotonEliminarLiga;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JButton BotonInsertarEqui;
    private javax.swing.JButton BotonInsertarLiga;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonModificarEqui;
    private javax.swing.JButton BotonModificarLiga;
    private javax.swing.JButton CancelarEqui;
    private javax.swing.JButton CancelarLiga;
    private javax.swing.JComboBox<String> ComboBoxEquipos;
    private javax.swing.JComboBox<String> ComboBoxLigas;
    private javax.swing.JButton ConfirmarEqui;
    private javax.swing.JButton ConfirmarLiga;
    private javax.swing.JTextField DniFut;
    private javax.swing.JTextField DniFutb;
    private javax.swing.JTextField EdadFut;
    private javax.swing.JTextField EquiposLiga;
    private javax.swing.JTextField EstadioEqui;
    private javax.swing.JTextField FinLiga;
    private javax.swing.JTextField FundacionEqui;
    private javax.swing.JTextField IdEqui;
    private javax.swing.JTextField IdEquiposLiga;
    private javax.swing.JTextField IdLiga;
    private javax.swing.JTextField InicioLiga;
    private javax.swing.JTextField NombreEqui;
    private javax.swing.JTextField NombreFut;
    private javax.swing.JTextField NombreLiga;
    private javax.swing.JTextField SociosEqui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableEqui;
    private javax.swing.JTable jTableLiga;
    // End of variables declaration//GEN-END:variables
}
